from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);")
        MainWindow.setAnimated(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.centralWidget.setObjectName("centralWidget")
        self.priceLabel = QtWidgets.QLabel(self.centralWidget)
        self.priceLabel.setGeometry(QtCore.QRect(110, 110, 241, 31))
        self.priceLabel.setStyleSheet("font-size:18pt; color: white;")
        self.priceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.priceLabel.setObjectName("priceLabel")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber.setGeometry(QtCore.QRect(580, 140, 121, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 240, 161, 161))
        self.pushButton.setStyleSheet("QPushButton { font-size: 30px; background-color: white; color: black; border-style: solid; border-color: red; border-width: 1px }")
        self.pushButton.setObjectName("pushButton")
        self.qrLabel = QtWidgets.QLabel(self.centralWidget)
        self.qrLabel.setGeometry(QtCore.QRect(80, 150, 300, 300))
        self.qrLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qrLabel.setStyleSheet("")
        self.qrLabel.setText("")
        self.qrLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.qrLabel.setObjectName("qrLabel")
        self.titleLabel = QtWidgets.QLabel(self.centralWidget)
        self.titleLabel.setGeometry(QtCore.QRect(30, 20, 401, 81))
        self.titleLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleLabel.setStyleSheet("font-size:60pt; font-style:italic; color:white;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.numberLabel = QtWidgets.QLabel(self.centralWidget)
        self.numberLabel.setGeometry(QtCore.QRect(550, 60, 171, 41))
        self.numberLabel.setStyleSheet("font-size:24pt; color: white;")
        self.numberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numberLabel.setObjectName("numberLabel")
        self.nodeInfoLabel = QtWidgets.QLabel(self.centralWidget)
        self.nodeInfoLabel.setGeometry(QtCore.QRect(438, 450, 351, 20))
        self.nodeInfoLabel.setStyleSheet("color: white")
        self.nodeInfoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nodeInfoLabel.setObjectName("nodeInfoLabel")
        self.closeButton = QtWidgets.QPushButton(self.centralWidget)
        self.closeButton.setGeometry(QtCore.QRect(730, 10, 64, 64))
        self.closeButton.setStyleSheet("color: transparent; border: none")
        self.closeButton.setObjectName("closeButton")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pay2Pour"))
        self.priceLabel.setText(_translate("MainWindow", "1 Drink = 0.01 ETH"))
        self.pushButton.setText(_translate("MainWindow", "Pour"))
        self.titleLabel.setText(_translate("MainWindow", "Pay 2 Pour"))
        self.numberLabel.setText(_translate("MainWindow", "# of drinks"))
        self.nodeInfoLabel.setText(_translate("MainWindow", "Not connected"))
        self.closeButton.setText(_translate("MainWindow", "X"))